### ISSUE TITLE
Is it possible to get email messages to work like the tabs in the new gmail layout?

### ISSUE THREAD

**Issue by MostHated** [Midnight-Lizard/Midnight-Lizard#122]
Hello,
    I just switched to the new gmail layout today and its much better looking when using MidnightLizard now, one thing I see that I really like is the tabs show up different colors and you can easily see them instead of everything being pretty much the same color. I was wondering if there is a way to make new messages show up a bit more discernable from read messages similar to how these tabs look now.

Though I did just notice now that at least the background becomes darker, which helps. The normal mail layout made it really hard to tell the difference. Would still be nice to have a color difference.

![How it looks now.](https://i.imgur.com/pi3SHbb.png)

![Another tab](https://i.imgur.com/rilPukG.png)

**Comment by pavel-agarkov** [comment]
I can change the role for unread messages background to be a `button`
So you will be able to control its color, contrast, etc... with settings for buttons.
For example it might look like this:
![image](https://user-images.githubusercontent.com/24639631/41127237-e1a5961c-6ab2-11e8-9227-cae7ccbf0cdd.png)
I can include this change in the next minor release. (Since I have just implemented it)

**Comment by MostHated** [comment]
That would work great, thank you!
