### ISSUE TITLE
Editing/Deleting Custom Themes has no effect

### ISSUE THREAD

**Issue by BreadYogurt** [Midnight-Lizard/Midnight-Lizard#127]
Not sure if I'm doing it right because the UI is confusing, but attempting to update or delete a custom theme does not do anything. I'm using Firefox.

**Comment by pavel-agarkov** [comment]
Please describe what you are doing step by step.
If you are confused with absence of some message boxes - I removed some of them since they were destructive, but everything works as designed.
When you (update/delete) any theme it gets immediately (updated/reverted to default) on the page where it is used even if it is not the current page.

**Comment by pavel-agarkov** [comment]
And a deleted color scheme stays applied on the popup so you still can save/apply/export it before closing the popup.

**Comment by pavel-agarkov** [comment]
Please reopen this issue if problem is still relevant.
Thank you.
