### ISSUE TITLE
Opt-in/out for automatic options in 9.3 

### ISSUE THREAD

**Issue by lonix1** [Midnight-Lizard/Midnight-Lizard#132]
The [latest release's changelog](https://github.com/Midnight-Lizard/Midnight-Lizard/releases/tag/9.3) includes:

    ✔ Automatic installation and update
    ✔ Automatic color scheme changes appliance
    ✔ Automatic schedule appliance

Please let me opt-in/out of this in the settings. I don't want an extension doing anything without my permission. Also please explain what the above means, because it isn't clear.

**Comment by pavel-agarkov** [comment]
All extensions get updated automatically by the browser.
Some browsers allow users to control this process, but Chrome doesn't.
If you are using some other browser where you can disable automatic extensions update then Midnight Lizard won't be automatically updated there.
You copied just a part of the log entry:
```
🆕 No need for page refresh any more:
  ✔ Automatic installation and update
  ✔ Automatic color scheme changes appliance
  ✔ Automatic schedule appliance
```
Previously the process was broken in the middle and you had to refresh the page in order to complete installation, update, color scheme update and schedule pursuit.
But now the process will be completed automatically as it should be doing from the beginning.
It doesn't start the process (you or browser do) - extension just completes it automatically.
So it does nothing you haven't allowed it to do already.

**Comment by lonix1** [comment]
Hi @pavel-agarkov I'm using firefox, and it lets me disable automatic extensions update.

So to be sure I understand you, the "automatic" process does not apply to me - I need to do it manually? (which is what I prefer).

thanks
