### ISSUE TITLE
Buttons on XDA posts are removed

### ISSUE THREAD

**Issue by Koolstr** [Midnight-Lizard/Midnight-Lizard#138]
I'm finding this to be quite a peculiar bug. On the [XDA Developers forum](https://forum.xda-developers.com), the buttons on a post (for things like reply, thank, etc.) were missing. Turning off/excluding the site from Midnight Lizard immediately restores the presence of the buttons. They aren't just made invisible due to my dark theme; the elements themselves are genuinely removed/hidden. Please figure out what is causing this.

Theme active:
![2018-07-06 14_16_33- rom op3_3t oreo resurrection remix 6 1 0 unofficial microg ota - post 3](https://user-images.githubusercontent.com/2044760/42394567-8b090960-8128-11e8-9965-9c362122bc9f.png)

Theme disabled:
![2018-07-06 14_16_47- rom op3_3t oreo resurrection remix 6 1 0 unofficial microg ota - post 3](https://user-images.githubusercontent.com/2044760/42394571-8e77b420-8128-11e8-8a0b-e152ec4909a2.png)

**Comment by pavel-agarkov** [comment]
The problem is not with Midnight Lizard itself.
It is ad blockers who hides those buttons.
If you disable ad blockers on this website the problem will gone.
I used to successfully fight with some of them for the facebook but I don't think it's a good idea - there are too many of ad blockers and pages...

**Comment by Koolstr** [comment]
Wow, you were right. My adblocker was the source of the problem. But why then would toggling your extension affect its visibility? That's a pretty odd overlap.
I am impressed that you were actively discussing with adblocker companies to resolve this problem. Why not fight for it, but only for the most-used adblockers? It can have a substantial effect across a lot of your userbase, so I think it is worth the time to fight for it with those adblockers.

**Comment by pavel-agarkov** [comment]
Visibility is affected because after applying styles on those elements adblockers start considering them as ads and hide. They have very weird rule: everything that has inline style is an ad... On facebook it was causing the whole page to disappear.
By fighting I meant doing it with my code😄 They won't even listen...
But the way I did it with code impacted page performance so it is much better to disable adblockers instead.
Not this time but Midnight Lizard's simplified mode might also help with adblockers since it does not use inline styles that much.

**Comment by Koolstr** [comment]
That actually makes sense, how they can be connected. But that's a pretty bad way to identify ads, IMO.
Oh, well that is still better than nothing lol.
I can see how it might impact performance. You might want to include a notice in the extension that tells people to try disabling their adblocker if buttons are missing. 
Simplified Mode does not help, in this case.
