### ISSUE TITLE
Popup loading and live themeing delayed on Firefox

### ISSUE THREAD

**Issue by Koolstr** [Midnight-Lizard/Midnight-Lizard#140]
On Chrome, when I open the ML settings popup, the active theme is already applied and the settings are instantly clickable/accessible. In contrast, on Firefox, when I click on it, it remains darkened for a few moments before the active theme gets applied. During that time, nothing inside the popup can be clicked.

This issue of either delayed (or slower) themeing seems to apply to general site themeing as well. On any webpage on which it is active, the site is initially darkened for a few moments, before the theme is applied and the site is then usable.

Any idea what is going on here?

**Comment by pavel-agarkov** [comment]
After spending a lot of time trying to find what else can be a problem I tend to think that Firefox is just less performant. The darkening was actually introduced as a fix to this delay since it is much better then a white screen.
The same processing stages are used in Chrome as well but probably they are less noticeable there.
So in the future I will try to make common optimizations applicable to all browsers and it should help with this issue as well.

**Comment by Koolstr** [comment]
Cool. Let me know when they are done, and take your time.
By the way, somehow, with further use, ML has become more 'responsive' in FF. So this issue isn't too big a problem anymore.
Although, I do want to note that on loading some pages, the background is not initially black, so there is blinding white for a moment. And sometimes, the background is not changed until the very end of the page load, so there is light green text on a white background :/

**Comment by pavel-agarkov** [comment]
Most elements on most pages are actually transparent and only the top element has a white background.
For those pages Midnight Lizard works very well since you won't notice that it hasn't completed processing yet (because it is enough to change background just for a few elemets). There are a lot of different optimizations in Midnight Lizard which make it still good even if page has a lot of different areas filled with color but it is possible that you will notice a lag especially on Firefox and on big pages with dynamically loaded content.
But simplified mode should completely fix this problem since it does not process each element - instead it applies styles globally to all elements at the same time - instantly. So sometimes you might want to switch to the simplified mode even though it lacks interactivity.

**Comment by Koolstr** [comment]
All right. I'll give that a try and report back. Thanks for the breakdown on how it works internally.
