### ISSUE TITLE
Confirm dialog closes Firefox addon popup window, resulting in settings not being saved

### ISSUE THREAD

**Issue by nekorug** [Midnight-Lizard/Midnight-Lizard#167]
Running: Midnight Lizard 10.0.0, Firefox 62.0.3 (64-bit) on Arch Linux, using X, i3wm.

### Steps to reproduce:

1. Open the add-on popup by clicking the icon in the browser UI.

2. Go to Global Settings.

3. Attempt to activate sync or try to uncheck "Change browser theme".

### What happens:

A javascript confirm dialog comes up, instantly closing the popup window. Your changed setting is thus not properly saved.

### What I expected to happen:

The setting should be saved and ideally the window shouldn't close.

---

I temporarily circumvented this by checking the "Disable popup auto-hide" option in Firefox's dev tools when debugging the app. Obviously this is not a satisfactory solution for most users.

**Comment by pavel-agarkov** [comment]
Popup does not get closed on Windows with the same Firefox version.
It should be considered as a Firefox bug.
Since I don't have a Linux set up right now - I would appreciate you to open an issue on bugzilla.mozilla.org
Thank you.

PS: There are a lot of other problems (on Windows as well) with popup being closed to soon. That's exactly why settings import from file is not supported in Firefox - popup gets closed even before open file dialog appears. Surprisingly it stays opened when you open a link from popup (like GitHub link).

**Comment by pavel-agarkov** [comment]
Please reopen it if you would have a new info.
