### ISSUE TITLE
Apply color scheme to "New Tab"

### ISSUE THREAD

**Issue by Markus-N** [Midnight-Lizard/Midnight-Lizard#209]
I'm one of those users always having lots of browser windows with lots of tabs. In order to speed up browser start, the browser is set to "don't load tabs until touched", and every window has an empty "New Tab" as first tab. This way, the browser only needs to create the windows, and doesn't need to load anything.
After browser start, all windows have a normal-colored (i.e. white) "New Tab". When I switch to the second tab, wait until it's loaded, and the switch back to the first tab, it goes dark.

Opening a "New Tab" using the "+" icon or CTRL-T opens a tab that never goes dark. Also, the The first "New Tab" when opening a new window never goes dark, even after loading a page in a second tab.
I have found one interesting effect: If I use "Duplicate Tab" from an empty tab's context menu, the new tab _is_ dark initially.

I think it would be nice if all "New Tab"s could be dark initially.

Browser: Firefox 64.0.2

**Comment by pavel-agarkov** [comment]
Hi! I think extension don't have access to 'New Tab' unless they completely replace it.
So in order to have a dark 'New Tab' you have to also install some other extension like 'New Tab Tools'.
I do use this extension as well and everything works fine: first tab is always dark whether it is 'New Tab' or some other website. 'New Tab' is dark since 'New Tab Tools' has dark theme and all other websites are processed by 'Midnight Lizard' so they are dark too.

PS: Feel free to reopen or add comments to this issue if necessary.
