### ISSUE TITLE
Opening the plugin will add extra code in the WordPress editor.

### ISSUE THREAD

**Issue by StarryLeo** [Midnight-Lizard/Midnight-Lizard#222]
Hi, everyone.

Thank you for your great work. This plugin has worked very well on many web pages.

But, It causes a lot of trouble today. When I edited my article using WordPress's default editor, I switched from visual mode to text mode, and I found that this plugin adds a lot of extra code to break my article layout. 

Finally, the history of the WordPress editor saved me, I found the old version of the article before opening this plugin. Fortunately, I don't need a lot of re-editing. I hope that you can pay attention to this bug.

- Plugin version  10.2.0

- WordPress version  4.9.8

some extra code like, and these extra code in WordPress text mode is twice my original.(8000words)

`<a style="--link-color: #75b6ea !important; --link-color-hover: #90c4ee !important; --link-color-active: #71b3ea !important; --visited-color: #a075ea !important; --visited-color-hover: #b390ee !important; --visited-color-active: #9d71ea !important; --original-color: #000000; --original-background-color: rgba(0, 0, 0, 0);"`
`<a style="--link-color: #75b6ea !important; --link-color-hover: #90c4ee !important; --link-color-active: #71b3ea !important; --visited-color: #a075ea !important; --visited-color-hover: #b390ee !important; --visited-color-active: #9d71ea !important; --original-color: #000000; --original-background-color: rgba(0, 0, 0, 0);" href=""></a> <a style="--link-color: #75b6ea !important; --link-color-hover: #90c4ee !important; --link-color-active: #71b3ea !important; --visited-color: #a075ea !important; --visited-color-hover: #b390ee !important; --visited-color-active: #9d71ea !important; --original-color: #000000; --original-background-color: rgba(0, 0, 0, 0);"`
`<h2 style="--original-color: #333333; --original-background-color: #ffffff;">`

**Comment by pavel-agarkov** [comment]
Hi! Thank you for the report!
I don't use WordPress to check what exactly is happening, but as for other websites with content editing: normally Midnight Lizard manages to remove all that extra markup before content is saved.
Probably WordPress works somehow else, but in any case all that extra markup does absolutely no harm to the viewer despite slightly bigger source code size - which is negligible due to the compression.
Only Midnight Lizard understands all those custom properties - browsers will just ignore them.

Anyways I'm going to add a new processing mode in the next upcoming Midnight Lizard's version and this mode won't produce any extra markup so you can safely use it on any website with content editing.
You will be able to switch mode like this:
![image](https://user-images.githubusercontent.com/24639631/53424844-0a0e7080-39f5-11e9-8519-7955c9186ea5.png)

**Comment by pavel-agarkov** [comment]
I've release the new version today.
If you're using Firefox then just update Midnight Lizard to get the new version.
In case of Chromium-based browsers - you most likely would need to reinstall it to get the new version.
I would appreciate any feedback regarding the new Filter mode.
Thank you.

**Comment by pavel-agarkov** [comment]
closing by now
feel free to comment
