### ISSUE TITLE
unusable on mewe.com

### ISSUE THREAD

**Issue by pjhalsli** [Midnight-Lizard/Midnight-Lizard#227]
On a site like Mewe the themes is  unusable.   Somehow the themes block out visual stuff on the site - like notifications and emojis.  

Here's two pics with ML enabled and disabled to show what I mean
https://imgur.com/a/LUHGAAa

**Comment by pavel-agarkov** [comment]
I cannot test it since this website does not seam to work even without Midnight Lizard:
![image](https://user-images.githubusercontent.com/24639631/54487591-dfebf800-48a8-11e9-84e1-c889c911c2e5.png)

Anyway from your image it looks like Simplified mode has been used so you can try to switch the mode:
![image](https://user-images.githubusercontent.com/24639631/54487570-a4e9c480-48a8-11e9-9033-e5f987702249.png)
Filter or Complex modes should do a better work here.

Let me know if it helped.

**Comment by pjhalsli** [comment]
you're the best  -  it works just fine now.  Thank you so much
