### ISSUE TITLE
UI bug: browser.display.use_document_fonts

### ISSUE THREAD

**Issue by atomGit** [Midnight-Lizard/Midnight-Lizard#228]
if `browser.display.use_document_fonts` = 0 then the content/text in the pop-up UI runs off the end of the window

https://i.imgtc.com/TsEnH2v.png

using fonts specified by a website is a privacy issue

**Comment by pavel-agarkov** [comment]
Midnight Lizard does not use web-fonts.
The following font families are used: Arial, Helvetica, sans-serif - they are local and does not compromise user privacy.
There is no way I can adjust to all possible fonts user might have specified since there is a popup window size limitations and Midnight Lizard has reached them already.
