### ISSUE TITLE
bug? : shaded embed elements

### ISSUE THREAD

**Issue by atomGit** [Midnight-Lizard/Midnight-Lizard#229]
FF 66 ML 10.3.6
i use the simplified processing mode by default and have disabled image shading, however embedded videos are still shaded sometimes and it appears there is no way to un-shade them - example: https://invidio.us/watch?v=xa0TTuICrYU

**Comment by pavel-agarkov** [comment]
Do you mean that video is dimmed before you start watching it?
If so - it is a correct behavior since before you start playing it you have a background image over the video area. You can fix this by removing brightness and saturation limits from background (fond) images as well:
![image](https://user-images.githubusercontent.com/24639631/56320542-1e592900-616d-11e9-956e-58695e5d1353.png)

**Comment by pavel-agarkov** [comment]
I missed that you are using a simplified mode - you cannot fix this problem in simplified mode since there are multiple layers over the video (most likely ads) but simplified mode sets some background to all elements even if they were transparent originally - that's the main trick why it works faster - it does not check original styles and changes everything.
So you need to switch the mode back to Auto or Complex at least for this website.

**Comment by atomGit** [comment]
> Do you mean that video is dimmed before you start watching it?

i meant even while it's playing

> You can fix this by removing brightness and saturation limits from background (fond) images as well

that seems to cure the problem

> I missed that you are using a simplified mode - you cannot fix this problem in simplified mode since there are multiple layers over the video (most likely ads) 

i use uBlock O, so no ads, and it appears the fond tweak solved the problem - i set bright and sat to 100% and tested ok

hell of an extension BTW - i hadn't expected something so featured to work this well, but when using simplified mode the 'white flash syndrome' is all but extinct
