### ISSUE TITLE
basecamp browser failure

### ISSUE THREAD

**Issue by mctopherganesh** [Midnight-Lizard/Midnight-Lizard#240]
Hey there,

First issue ever but I love your extension so far and so I just want to make aware an issue I'm having.

I use basecamp for a client I work with and the color scheme does not allow me to use text boxes and freezes my browser and then does the "chrome has crash send a report" thingy.

I know that you can change the settings per site but I've only found that you have to actually be ON that site to change the settings. When I'm on Basecamp I am not able to access any of the settings and it seems frozen.

I suppose a solution to this would be, is there a way to change the global settings for a specific site without being on that site?

**Comment by pavel-agarkov** [comment]
You can disable Midnight Lizard globally and then go to Basecamp and disable it there as well by keyboard shortcut Alt+Shift+L or by clicking on the website title in the Midnight Lizard's settings popup header. After that just enable it globally back.
You can also use exclude match patterns to exclude this website globally as well so that you would not need to go there to disable it.
