### ISSUE TITLE
Keep text colors when increasing contrast

### ISSUE THREAD

**Issue by federico-terzi** [Midnight-Lizard/Midnight-Lizard#246]
Hey,
First of all, thank you very much for the awesome extension!
I'm currently struggling with colored text and I can't find any option to fix it. In particular, when  I visit a website which includes Syntax Highlighting (such as Github):

![image](https://user-images.githubusercontent.com/20475953/71594630-e9dd9f80-2b38-11ea-95b6-5e6b05e40da8.png)

And I turn Midnight Lizard on, the colors disappear:
![image](https://user-images.githubusercontent.com/20475953/71594524-8fdcda00-2b38-11ea-915a-bf3eb836ae32.png)

It seems like the only option to bring them back is to decrease the `Contrast` option, but this cause the text to become unreadable:
![image](https://user-images.githubusercontent.com/20475953/71594540-9ff4b980-2b38-11ea-998d-e78180758a8d.png)

Is there any way to turn the black text to white while keeping the colors?

I'm currently using Chrome.

Thanks again for your work! :)

**Comment by pavel-agarkov** [comment]
There might be several different reasons for that:
1) page is big enough for Midnight Lizard to switch to `Simplified` mode - you can try to explicitly set processing mode to be `Complex` or `Filter` to fix this 
![image](https://user-images.githubusercontent.com/24639631/71976300-05c2fe80-3227-11ea-9874-8a87408cfd56.png)

2) you are using color scheme like `Inverted Grayscale` witch disables original text colors - you have to use another color scheme at least for websites with code
2) you are using your own custom made color scheme witch has suboptimal text settings - you can try to send it to me so I can fix it, but since I don't know what you wanted to achieve with this custom color scheme I will most likely break it by fixing :) ([here is how you can export color scheme](https://groups.google.com/forum/#!topic/midnight-lizard-support/If-uji8fZ0w))

**Comment by pavel-agarkov** [comment]
here are text settings optimizations for syntax highlighting:
![image](https://user-images.githubusercontent.com/24639631/71976934-a665ee00-3228-11ea-8c43-fdd9fa4dbcd1.png)

**Comment by federico-terzi** [comment]
Thank you very much @pavel-agarkov, that worked great :)
Thanks again for your wonderful job
