### ISSUE TITLE
Visited Link Hue not respecting hue gravity

### ISSUE THREAD

**Issue by digiwombat** [Midnight-Lizard/Midnight-Lizard#248]
The Visited Link Hue option applies to all visited links regardless of Visited Hue gravity.

This makes things look pretty bad on sites where the visited link hue doesn't vibe with the rest of the site and I'm not doing a full re-color. Setting this per-site is a lot of work considering there is already an option to essentially ignore link re-coloring for normal links.

If this is expected behavior, then I'd like to request that a Visited Hue Gravity option be added.

**Comment by pavel-agarkov** [comment]
There is no way to get the original visited links color due to [security reasons](https://developer.mozilla.org/en-US/docs/Web/CSS/Privacy_and_the_:visited_selector). Hue gravity works only when there is the original color that gets moved towards the desired one. But since the original color for visited links cannot be obtained there is no way to apply hue gravity on it.
