### ISSUE TITLE
Support OSX Theme sync

### ISSUE THREAD

**Issue by fathom-matthew** [Midnight-Lizard/Midnight-Lizard#253]
Recently OSX 10.15 Catalina updated to support auto dark mode, [which is accessible through the AppKit SDK](https://stackoverflow.com/questions/57303286/how-to-detect-if-osx-in-dark-or-light-mode-in-auto-appearance-mode-in-catalina). The [Night Eye extension](https://chrome.google.com/webstore/detail/night-eye-dark-mode-on-an/alncdjedloppbablonallfbkeiknmkdi?hl=en) already supports this feature. It would be cool if Midnight Lizard was updated to support this functionality to reduce the amount of time OSX users get white-flashed by chrome/applications during sunrise/sunset!

**Comment by pavel-agarkov** [comment]
It can be done via [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme), but should not be used by default since user might not have any system wide schedule and Midnight Lizard won't work at any time. So we need to add a new configuration parameter on the global settings tab: `Use system schedule` unchecked by default.
