### ISSUE TITLE
Does this addon make external requests?

### ISSUE THREAD

**Issue by eloyesp** [Midnight-Lizard/Midnight-Lizard#272]
I'm not sure if this add-on could compromise security or privacy by using external style-sheets or making any requests to some server (to keep styles updated for example), that could be used to track users. Whatever answer it has, I think that adding that info on the readme or the add-on description (as a feature or anti-feature) to help people chose. Regards.

**Comment by pavel-agarkov** [comment]
Midnight Lizard does not make any requests to the server since it doesn't have one.
Also there are no external stylesheets for the same reason.
You can find details in [Privacy Policy](https://midnight-lizard.org/extension-privacy), but it is impossible to list there all activities that Midnight Lizard does not do...
