### ISSUE TITLE
Isn't working on mozilla support pages

### ISSUE THREAD

**Issue by hiteshsharma** [Midnight-Lizard/Midnight-Lizard#277]
Not working on mozilla support pages. Try this one https://support.mozilla.org/en-US/questions/1261804
I checked all my settings and I don't have any custom settings for support.mozilla.org

**Comment by pavel-agarkov** [comment]
Yes, browser vendors do a very pure job conveying to users where they can use extensions and where it is forbidden due to security reasons. Basically all browser system pages, web store and other parts the of vendor website are forbidden by each vendor. For that specific reason I do use Chrome to browse Firefox add-ons and vice versa😂
