### ISSUE TITLE
"Fond images" in English translation

### ISSUE THREAD

**Issue by chrisgraham** [Midnight-Lizard/Midnight-Lizard#279]
"Fond" is French for Background, very few English readers will understand that. I suggest for the English say "Bg images", that will fit nicely and be understood.

**Comment by pavel-agarkov** [comment]
It is actually from Latin _fundus_ and is present in most European languages as well as in English.
https://en.wiktionary.org/wiki/fond
Yes, it is rarely used this way in English nowadays and I was very skeptical about it. But some users I've asked told me that since English is used by default when there is no translation into their language yet then _fond_ is better than _bg_ abbreviation for them. Yes, I actually already considered using _bg_.

**Comment by chrisgraham** [comment]
That's smart :).

The thing about English is that there are so many influences (French, Greek, Latin, Old English, etc), there are far more words than people actually know or use. So something being in a dictionary doesn't mean a lot sometimes :D. I've definitely not heard it.

I won't say what you should do, your explanation makes sense, I can just give my perspective as a native speaker.

**Comment by pavel-agarkov** [comment]
Here people can propose and vote for the translations:
https://translate.midnight-lizard.org/translate/midnight-lizard/4/en-en#q=fond

There are many other mistakes I've made since I'm not a native English speaker. So I would love to hear more from you.

**Comment by chrisgraham** [comment]
Your English is generally good.
I made a few suggestions on the translation app.
"Buttons' --> "Button faces"
"Minimal" --> "Minimum"
I explained the reasoning on the translation app in comments there.
