### ISSUE TITLE
High contrast theme has low contrast on buttons

### ISSUE THREAD

**Issue by chrisgraham** [Midnight-Lizard/Midnight-Lizard#280]
This seems like a bug. A user who wants high contrast will want the contrast setting for everything to be reasonably high, but for buttons it is explicitly set to low to reduce contrast.

**Comment by pavel-agarkov** [comment]
That was my take on contrast - if I increase button contrast against surrounding background then I also will have to change text on those buttons to keep text to button background contrast ratio. But very fast I won't be able to do so without going all in for dark buttons. I didn't like it so in the default scheme I stick with low button background contrast and high text contrast instead. But there is nothing stopping users from changing it as they like - that's why we have all those settings.

**Comment by chrisgraham** [comment]
Thanks Pavel. I think some of the issues I created were a result of me being confused about what stuff means, possibly I tuned some settings incorrectly and the results seemed wrong due to me misunderstanding.
