### ISSUE TITLE
Option for disabling anti-contrast effects

### ISSUE THREAD

**Issue by chrisgraham** [Midnight-Lizard/Midnight-Lizard#281]
Websites may use:
 - Background-image gradients (linear-gradient etc)
 - Text-shadow
 - Box-shadow

All these may reduce perceived contrast for users with vision impairments. It would be great to have an options to simply have each of these styles stripped, and turn on for the low contrast theme by default.

EDIT: For background-image gradients it should only strip it if there's a background-color set that it will then fall back to. I think right now background-image gradients are not parsed for contrast alteration, which also would be a nice feature for you to support.

**Comment by pavel-agarkov** [comment]
Background-image gradients are processed right now in Complex  and Simplified modes as backgrounds (each color separately) and is used then to determine text color on top of it.
Text-shadows are also processed. Only box-shadow is ignored right now, since in most cases it is used only for elevation and is black by default so it looks good on the dark side as well.
