### ISSUE TITLE
Disabling special link color adjustment

### ISSUE THREAD

**Issue by chrisgraham** [Midnight-Lizard/Midnight-Lizard#282]
![Screenshot from 2020-06-07 19-32-49](https://user-images.githubusercontent.com/195389/83983644-b7a94880-a8f5-11ea-8616-131c08d4ba64.png)
Hi,
From what I can tell, the configuration for setting link color cannot be disabled. I'd like link text to be adjusted exactly like regular text is adjusted. At the moment it actually works against high-contrast functionality, as the configured link color may work badly against the background behind it.

Edit: Attached a screenshot of it really messing up CkEditor due to this.

**Comment by pavel-agarkov** [comment]
Links color is processed in a very similar manner as text right now so it also depends on the background very much.
Please provide a link where this problem is present so I can investigate more.
I cannot reproduce it on their demo
![image](https://user-images.githubusercontent.com/24639631/84483385-efbbdd00-aca1-11ea-9b66-828ffa67ae35.png)

**Comment by chrisgraham** [comment]
I can no longer reproduce either. I'll reopen if I can reproduce again.
