### ISSUE TITLE
Prefer to toggle website's native darkmode

### ISSUE THREAD

**Issue by key-equivalent** [Midnight-Lizard/Midnight-Lizard#285]
Would it be possible for the extension to detect if a website has a native dark mode, and if so prefer for the extension to toggle that on instead of using a custom color scheme?  I feel like that would be a smoother experience on those types of sites

**Comment by pavel-agarkov** [comment]
Yes, when I started to use scheduled activation it turned out that on those websites where Midnight Lizard is disabled dark mode would not switch automatically and I have to do it manually. But unless I'm using schedule and turn Midnight Lizard off periodically I don't have problems with the fact that I need to disable it on some websites and use their built-in dark modes. Is it true for you as well?
If so the better way would be to use system schedule then Midnight Lizard will be activated automatically as well as those websites will automatically activate their dark modes. The industry is not there yet but I believe it will be [soon](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme).
But I don't believe that writing custom code for every website to toggle its own themes is sustainable in a long run. I've tried to alter some websites with custom CSS styles (and still do in some extend) but it requires to constantly release updates to fix those styles since websites never stop updating their markup and styles so mine become broken from time to time. Code to switch built-in themes will be even more complicated and prone to change thus difficult to support.

**Comment by key-equivalent** [comment]
As an alternative, could the plugin check to see if the background color is already sufficiently dark, or if the average color on the page is sufficiently dark, and if so disable itself so as not to be redundant with a native dark mode?

**Comment by pavel-agarkov** [comment]
Midnight Lizard starts processing even before original styles are downloaded so it cannot sufficiently verify whether the page was dark already.
