### ISSUE TITLE
ML is activating on some parts of a website even when turned off

### ISSUE THREAD

**Issue by Luk164** [Midnight-Lizard/Midnight-Lizard#289]
Some websites, like azure portal, feature a website-inside-website interface. This means that when I have the "apply to all sites by default" setting turned on, disabling ML for the website only works for the outermost part of the website.

The attached screenshots show the difference between global setting on and off while website is blacklisted the whole time.

![image](https://user-images.githubusercontent.com/30559213/88145834-59ad9780-cbfb-11ea-9091-a8bef900537f.png)
![image](https://user-images.githubusercontent.com/30559213/88145874-6631f000-cbfb-11ea-85a8-ce7db7f37316.png)

**Comment by Luk164** [comment]
Note: For this site, inspecting element allowed me to blacklist https://monitor-afd.hosting.portal.azure.net/, which is the inner website in this case, which fixed the issue for this particular site.

**Comment by pavel-agarkov** [comment]
When you apply changes to the current website it also applies the same changes to all visible at that moment inner websites.
But those that were not visible at that moment will still use settings previously applied to them.
Specifically for azure portal you can add exclude rule to the default color scheme:  https://*.azure.net/*
![image](https://user-images.githubusercontent.com/24639631/88170423-5a0f5800-cc26-11ea-85c6-1c42b26f618f.png)
This way all subdomains will be disabled as well.
After adding exclude rule you need to press "Save" button if there is one otherwise "Set as default"
