### ISSUE TITLE
QuotaExceededError when diabling MidLiz for a website

### ISSUE THREAD

**Issue by Trollwut** [Midnight-Lizard/Midnight-Lizard#303]
Hey mates!

Since the last update of my Firefox (to version 80.0.1), whenever I disable Midnight Lizard for one specific site, I get this error instead:

    Midnight Lizard
    Settings application failed. Refresh the page and try again.
    QuotaExceededError: storage.sync API call exceeded its quota limitations.

When I reload the site, the changes are NOT made and Midnight Lizard is again activated for this site.

Can someone explain me this error, if it's known and what I can do against it?

**Comment by pavel-agarkov** [comment]
It might be difficult to change the way you use Midnight Lizard to fix this problem so the simple solution is to switch to local data storage instead of sync one (just uncheck **Sync settings across your devices**):
![image](https://user-images.githubusercontent.com/24639631/94360341-30a2fa80-00b5-11eb-85cb-36b7ce1e4e5b.png)

**Comment by Trollwut** [comment]
That indeed "fixed" it, thanks!

So it's that MidLiz syncs too much size of data to Firefox account, am I right?

AFAIK they lowered the limits per addon in the last few updates (I guess version 79?), so this is a bummer. But at least I can use it right now. :)

**Comment by pavel-agarkov** [comment]
@Trollwut yes, you are right.
And Midnight Lizard uses the most when unnamed custom color scheme is used as default one.
This way it will be copied to website settings when user disables Midnight Lizard on that website.
There is no problem when built in or made by user named color schemes is used since they are stored just once.

**Comment by Trollwut** [comment]
Wait, you're right...

While I imported "Dracula" colorscheme as set it as default, it somehow now is shown as "Custom". So this is exactly the problem you're describing.

So I guess my best guess is to reset all website-specific settings and then just turn it off for each website again, so it can sync again without problems?

**Comment by pavel-agarkov** [comment]
Named color scheme becomes Custom if you change it and then press Apply instead of Save.
So yes, if you switch back to sync, then delete all website settings and set again Dracula as default color scheme - you will be good to go.

**Comment by Trollwut** [comment]
Alright, did this and for now it seems everything's working as expectet. Thanks for your help! :) 

For future readers: **Don't forget to restart your browser after you set your scheme as default!** It seems like already-opened tabs still have the "Custom" option enabled instead of the "Default".
