### ISSUE TITLE
Global black and white list mode

### ISSUE THREAD

**Issue by lhj5426** [Midnight-Lizard/Midnight-Lizard#319]
Can the current pseudo black and white list mode add a global black and white list mode that is judged by the URL. For example, I have 20 common websites that need to be set globally for only these 20 websites to enable extensions. Other websites do not start extensions. Real black-and-white list mode Now every infrequently used website has to be closed by one click. It’s really troublesome. You can add such a black-and-white list.

**Comment by lhj5426** [comment]
Not a time-based black and white list, but a global full time URL-based black and white list mode

**Comment by pavel-agarkov** [comment]
If you have a list of 20 websites where you want to use Midnight Lizard and disable it for all other websites then the easies way is to use match patterns:

1. Select Default color scheme
![image](https://user-images.githubusercontent.com/24639631/105757928-b64d8e80-5f5f-11eb-8350-9073eb71ee5d.png)

2. Open Activation tab
3. Uncheck Run on this website
4. Add Include match patterns for all websites you want to Use Midnight Lizard on
5. Press Save (or Set as default if you don't have Save button)
![image](https://user-images.githubusercontent.com/24639631/105759086-109b1f00-5f61-11eb-9ba9-08e936fa5afc.png)

This behavior is described in the hint over the Include match pattern field:
![image](https://user-images.githubusercontent.com/24639631/105759440-899a7680-5f61-11eb-9ecb-e2d00e174eb5.png)

**Comment by JamesO2x** [comment]
This is exactly the kind of feature I was looking for. But for some reason the Match boxes are disabled (I can't edit the text inside of them). Is this a bug?

I'm using the latest version of Firefox, and would really love this feature.

**Comment by pavel-agarkov** [comment]
@JamesO2x if I understand the goal then you need to exclude: 
`https://*.itch.io/`

**Comment by JamesO2x** [comment]
@pavel-agarkov I'm sorry, I realize my last comment wasn't very clear. I'm including a screenshot to better visualize what I mean, and what the expected behavior should be:

[https://i.imgur.com/y5hJsZU.png](https://i.imgur.com/y5hJsZU.png)

At the top of this image, I've included a screenshot of the URL of the current site I am on. The bottom part shows that the rules in my Include section **and** the Exclude section are both registering as "true." This shouldn't be the case.

Both of these sites above (itch and Neocities) use the `https://username.sitename.com/` format. So when you are not currently on a user's page (or sub page), the URL changes to just `https://sitename.com/`

I want to be able to trigger my **exclude** rule on user pages like `jameso2.itch.io` **but not exclude** the base site at `itch.io` (URL's without the username preceding it).

But unfortunately, you can see that `https://*.itch.io/` rule is being triggered as **true** on the base site at: `https://itch.io/games`
You can see that it's triggering **true** in the image I linked above.

This doesn't seem to be correct behavior, since there is no dot "." before "itch" on the base site, so the rule `*.itch` shouldn't trigger on just `http://itch.io`. It's treating them as if they are identical URLs.

I want to be able to apply Midnight Lizard's dark theme to the base site (itch, or Neocities) but not to individual user pages. Since users on these sites are able to CSS style their own pages how ever they want, applying a single universal Midnight Lizard theme across **all of them** breaks a ton of user pages and makes them unreadable.

I hope this is more clear.

**Comment by pavel-agarkov** [comment]
This behavior is expected since I'm using the standard algorithm.
Here's screenshot from the match pattern syntax [docs](https://developer.chrome.com/docs/extensions/mv3/match_patterns/):
![image](https://user-images.githubusercontent.com/24639631/117618759-1666ea00-b177-11eb-8b1d-30d4ff8f3104.png)

But I agree that it is not useful for Midnight Lizard and should be changed.
I've fixed it and it will be available in the next release.

PS: in the new algorithm `https://*.domain.name/*` won't include `https://www.domain.name/` otherwise it is impossible to handle exclude for all subdomains only. Unfortunately there will be no documentation for this behavior...

**Comment by JamesO2x** [comment]
Thanks. This is good to know.

And yeah, a lot of website are just outright dropping the "www." from their URLs, since it isn't really necessary. Even this Github page is showing directly as https://github.com without a www. And I'm noticing more and more websites using the "username.websitename.com" format for URLs, meaning that just distinguishing the "website.com" domain part is gonna become less and less useful. Especially since these userpages can often be personalized in any style, they're effectively their own website in a CSS sense (like the bandcamp pages for example, any user can choose a white or black background, or any other color... so treating all these URLs the same and applying one dark theme rule just doesn't work for something like Midnight Lizard).

Anyway, thanks for addressing this. I'll be looking out for that update.
