### ISSUE TITLE
Feature request: Change font per website and add your own fonts

### ISSUE THREAD

**Issue by wolfgrrl** [Midnight-Lizard/Midnight-Lizard#363]
It would be amazing if this extension would be able to change font per website and also allow the ability to upload your own fonts as well. Thank you!

**Comment by pavel-agarkov** [comment]
I don't think it's a good idea - there should be an independent extension for fonts.

**Comment by wolfgrrl** [comment]
If there was another extension, I would not have added it is a request. While there is an extension that allows changing fonts, it does not allow adding your own fonts. And why wouldn't this extension be a perfect place to have everything all in one extension instead of running two separate ones?

**Comment by pavel-agarkov** [comment]
From technical point of view I would prefer to create a separate extension for that since adding to much functionality to the single extension makes it harder to update and more prone to bugs.
But unfortunately I don't have time to work on it now - I had to emigrate to a new country three times already just this year...

**Comment by wolfgrrl** [comment]
I'm sorry to hear about the emigration issues. I wish you the best of luck. I do have an old, unsupported extension that I'm using that was removed from the extension website a long time ago I've altered so that it continues to work. When you're ready, I can send the code to you. Best of luck.
