### ISSUE TITLE
Extension does not apply color scheme on new page load, requiring a reload to appear

### ISSUE THREAD

**Issue by dziban303** [Midnight-Lizard/Midnight-Lizard#372]
Starting about a month ago, Midnight Lizard will not reliably inject the color scheme when opening a new page. Reloading the page is necessary for the scheme to be applied. I'm not sure how to go about troubleshooting this. Can anyone offer some guidance?

Windows 10, using Brave v1.48.122 (Chromium 109.0.5414.87)

**Comment by alphapapa** [comment]
I recently started using this extension.  Has it been going on this long?  I'm noticing now that it doesn't even seem to properly disable itself when the global on/off switch is off--it still breaks GitHub's appearance and I have to reload the page to fix it.  Time to uninstall, I guess.

**Comment by pavel-agarkov** [comment]
Hi, extensions cannot process a new page unless they are registered as a custom new page UI.
Midnight Lizard does not provide a custom new page UI.
I personally use another extension for custom new page experience.

**Comment by alphapapa** [comment]
@pavel-agarkov You seem to be talking about custom "new tab" pages.  That is not what this issue is about.  This is about the extension just not working sometimes, but then it does work after reloading the page.

**Comment by pavel-agarkov** [comment]
oh, yeah, I had problems with global disable functionality as well but did not have time to debug it.
But I did not have any examples when Midnight Lizard would not apply a scheme.
If it is happening for a particular website please try to remove it's settings (Global settings->Delete current website settings)
If it is randomly happening for different websites please send me console logs from that page - maybe I can spot errors there...

**Comment by dziban303** [comment]
I stopped using the extension months ago after it became intermittent and I got no replies to this issue

**Comment by alphapapa** [comment]
@pavel-agarkov For me, it often happens on GitHub's notifications page:

1.  I load the notifications page.  Everything seems fine.
2. I click a notification.  Everything seems fine.
3. I click the back button.  I see the list of notifications, but the background color of the BODY element is wrong (white, when my GitHub settings enable its own dark mode), and none of the elements on the page do anything when clicked.
4. I refresh the page, and everything works fine.

I suspect it may be related to the usage of the HTML5 history API; maybe Midnight Lizard isn't correctly recognizing when a tab has changed location and isn't applying its changes correctly, or something like that.

Anyway, like dziban303, I had to uninstall the extension, because even when I had it globally disabled, the problem on the GitHub notifications page persisted.  It was doing more harm than good, for my usage.  I'm afraid I can't provide more information than that.
