### ISSUE TITLE
[deleted]

### ISSUE THREAD

**Issue by pmeaney** [Midnight-Lizard/Midnight-Lizard#384]
[deleted]

**Comment by pavel-agarkov** [comment]
No, as you can check in the repository, Midnight Lizard does not send any user data to any third party or even to Midnight Lizard servers itself since there are no Midnight Lizard servers at all...
Also since Midnight Lizard is a recommended extension, the source code was reviewed by Google and Mozilla personal, so it is 100% safe.
You might have some other extension or virus sending the data.

**Comment by pavel-agarkov** [comment]
If I understand correctly what Little Rat extension does - it shows that Midnight Lizard downloaded images from websites you've visited since it is a part of its job - Midnight Lizard does download and process images locally on your computer to make them darker or less saturated. Those images are not sent anywhere.
