### ISSUE TITLE
Options page not operable on Firefox

### ISSUE THREAD

**Issue by hackel** [Midnight-Lizard/Midnight-Lizard#75]
I'm running Midnight Lizard on Firefox 60 on Android.  Whenever I select Midnight Lizard from the application menu, the options page opens, but then I get a black overlay on top that says, "Midnight Lizard cannot connect to this page because of one of the following reasons

Web browser does not allow to run extensions on this page (e.g. Web Store, Settings, New Tab)"

This is exactly the case.  I don't believe extensions are allowed to run on moz-extension:// URLs, are they?

The extension still works fine with the default settings, but the inability to customise it definitely limits its usability.

![screenshot_20180506-025224](https://user-images.githubusercontent.com/583677/39671161-a66e71b6-50d8-11e8-8e76-c235aef9e577.png)

**Comment by pavel-agarkov** [comment]
The only way right now is to enable sync and change settings on your desktop.
I will try to allow at least to make changes into default settings (probably in release after next one)
The problem is that normally popup did search for active tab and ask it what the current settings are.
But on android popup is the current tab and it tries to ask itself...

**Comment by hackel** [comment]
Thanks for the explanation, I look forward to that.  I know the Mobile Firefox UI for extensions isn't ideal.  Extensions like uBlock Origin and Cookie Autodelete are able to determine the active tab in their popup windows, though, so hopefully it will be possible to implement!
